/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTrendsRouteImport } from './routes/_app/trends'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppStationsRouteImport } from './routes/_app/stations'
import { Route as AppScadaRouteImport } from './routes/_app/scada'
import { Route as AppRoutineRouteImport } from './routes/_app/routine'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppReadingsRouteImport } from './routes/_app/readings'
import { Route as AppIncidentsRouteImport } from './routes/_app/incidents'
import { Route as AppGeneratorRouteImport } from './routes/_app/generator'
import { Route as AppFirepumpRouteImport } from './routes/_app/firepump'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAvailabilityRouteImport } from './routes/_app/availability'
import { Route as ApiPublicAdminSetPasswordRouteImport } from './routes/api/public/admin-set-password'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsRoute = AppStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => AppRoute,
} as any)
const AppScadaRoute = AppScadaRouteImport.update({
  id: '/scada',
  path: '/scada',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutineRoute = AppRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingsRoute = AppReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorRoute = AppGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AppRoute,
} as any)
const AppFirepumpRoute = AppFirepumpRouteImport.update({
  id: '/firepump',
  path: '/firepump',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAvailabilityRoute = AppAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicAdminSetPasswordRoute =
  ApiPublicAdminSetPasswordRouteImport.update({
    id: '/api/public/admin-set-password',
    path: '/api/public/admin-set-password',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AppAvailabilityRoute
  '/dashboard': typeof AppDashboardRoute
  '/firepump': typeof AppFirepumpRoute
  '/generator': typeof AppGeneratorRoute
  '/incidents': typeof AppIncidentsRoute
  '/readings': typeof AppReadingsRoute
  '/reports': typeof AppReportsRoute
  '/routine': typeof AppRoutineRoute
  '/scada': typeof AppScadaRoute
  '/stations': typeof AppStationsRoute
  '/templates': typeof AppTemplatesRoute
  '/trends': typeof AppTrendsRoute
  '/users': typeof AppUsersRoute
  '/api/public/admin-set-password': typeof ApiPublicAdminSetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AppAvailabilityRoute
  '/dashboard': typeof AppDashboardRoute
  '/firepump': typeof AppFirepumpRoute
  '/generator': typeof AppGeneratorRoute
  '/incidents': typeof AppIncidentsRoute
  '/readings': typeof AppReadingsRoute
  '/reports': typeof AppReportsRoute
  '/routine': typeof AppRoutineRoute
  '/scada': typeof AppScadaRoute
  '/stations': typeof AppStationsRoute
  '/templates': typeof AppTemplatesRoute
  '/trends': typeof AppTrendsRoute
  '/users': typeof AppUsersRoute
  '/api/public/admin-set-password': typeof ApiPublicAdminSetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/availability': typeof AppAvailabilityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/firepump': typeof AppFirepumpRoute
  '/_app/generator': typeof AppGeneratorRoute
  '/_app/incidents': typeof AppIncidentsRoute
  '/_app/readings': typeof AppReadingsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/routine': typeof AppRoutineRoute
  '/_app/scada': typeof AppScadaRoute
  '/_app/stations': typeof AppStationsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/trends': typeof AppTrendsRoute
  '/_app/users': typeof AppUsersRoute
  '/api/public/admin-set-password': typeof ApiPublicAdminSetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/availability'
    | '/dashboard'
    | '/firepump'
    | '/generator'
    | '/incidents'
    | '/readings'
    | '/reports'
    | '/routine'
    | '/scada'
    | '/stations'
    | '/templates'
    | '/trends'
    | '/users'
    | '/api/public/admin-set-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/availability'
    | '/dashboard'
    | '/firepump'
    | '/generator'
    | '/incidents'
    | '/readings'
    | '/reports'
    | '/routine'
    | '/scada'
    | '/stations'
    | '/templates'
    | '/trends'
    | '/users'
    | '/api/public/admin-set-password'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/availability'
    | '/_app/dashboard'
    | '/_app/firepump'
    | '/_app/generator'
    | '/_app/incidents'
    | '/_app/readings'
    | '/_app/reports'
    | '/_app/routine'
    | '/_app/scada'
    | '/_app/stations'
    | '/_app/templates'
    | '/_app/trends'
    | '/_app/users'
    | '/api/public/admin-set-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAdminSetPasswordRoute: typeof ApiPublicAdminSetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trends': {
      id: '/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stations': {
      id: '/_app/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof AppStationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scada': {
      id: '/_app/scada'
      path: '/scada'
      fullPath: '/scada'
      preLoaderRoute: typeof AppScadaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routine': {
      id: '/_app/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof AppRoutineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/readings': {
      id: '/_app/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof AppReadingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generator': {
      id: '/_app/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AppGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/firepump': {
      id: '/_app/firepump'
      path: '/firepump'
      fullPath: '/firepump'
      preLoaderRoute: typeof AppFirepumpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/availability': {
      id: '/_app/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AppAvailabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/admin-set-password': {
      id: '/api/public/admin-set-password'
      path: '/api/public/admin-set-password'
      fullPath: '/api/public/admin-set-password'
      preLoaderRoute: typeof ApiPublicAdminSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAvailabilityRoute: typeof AppAvailabilityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFirepumpRoute: typeof AppFirepumpRoute
  AppGeneratorRoute: typeof AppGeneratorRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppReadingsRoute: typeof AppReadingsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoutineRoute: typeof AppRoutineRoute
  AppScadaRoute: typeof AppScadaRoute
  AppStationsRoute: typeof AppStationsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvailabilityRoute: AppAvailabilityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFirepumpRoute: AppFirepumpRoute,
  AppGeneratorRoute: AppGeneratorRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppReadingsRoute: AppReadingsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoutineRoute: AppRoutineRoute,
  AppScadaRoute: AppScadaRoute,
  AppStationsRoute: AppStationsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAdminSetPasswordRoute: ApiPublicAdminSetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
